module.exports[0] = require("./groups")
module.exports[1] = require("./friends")
module.exports[2] = require("./identities")
module.exports[3] = require("./connect")
module.exports[4] = require("./addrs")
module.exports[5] = require("./dht")
module.exports[6] = require("./ping")
module.exports[7] = require("./lb")